const express=require("express")
const app=express()
const mongoose=require('mongoose')
const helmet=require('helmet')
const morgan=require('morgan')
const cors=require('cors')
app.use(helmet())
app.use(morgan("common"))
app.use(express.json())
app.use(cors())
const dotenv=require('dotenv')
dotenv.config()
const usersRoute=require("./routes/user.js")
const authRoute=require("./routes/auth.js")
const postRoute=require("./routes/posts.js")
app.get("/",(req,res)=>{
	res.send("hello")
})
// const mongourl="mongodb+srv://ecommerce:ecommerce123@ecommerce.vct41n9.mongodb.net/"
mongoose.connect(process.env.MONGOURL,()=>{console.log("DB connnected")})
app.use("/userapi",usersRoute)
app.use("/authapi",authRoute)
app.use("/postapi",postRoute)
app.listen(2000,()=>{console.log("Server started")}) 

